version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: ./docker/Dockerfile
    container_name: lptrw-stage-3-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: lptrw-stage-3-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
  db:
    container_name: lptrw-stage-3-db
    image: mysql:8.0
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
